version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "google-analytics-realtime-newrelic"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bf0h82bnc83t"
s3_prefix = "google-analytics-realtime-newrelic"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

