AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  google-analytics-realtime

  SAM Template for google-analytics-realtime

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  GaRealtimeNrFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ga_realtime_nr/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        GaRealtimeNrSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: ga-realtime-nr-schedule
            Description: Run every 5 minutes
            Enabled: True

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GaRealtimeNrFunction:
    Description: "Google Analytics Realtime API New Relic Lambda Function ARN"
    Value: !GetAtt GaRealtimeNrFunction.Arn
  GaRealtimeNrFunctionIamRole:
    Description: "Implicit IAM Role created for Google Analytics Realtime API New Relic function"
    Value: !GetAtt GaRealtimeNrFunction.Arn
